### ISSUE TITLE
Fix path for background image for home page and player ID

### ISSUE THREAD

**Issue by jasminezanders211** [Stratgg/Stratgg#105]
- [ ] Fix the background image pathing on the home page 
- [ ] Fix the background image pathing on ID the page

**Comment by SchoolyB** [comment]
Re-opening due to finding more images with incorrect paths. Fixing now
![Screenshot_25](https://github.com/Stratgg/Stratgg/assets/110133622/eb8c795e-5813-47f8-b5c3-00d520d2d92f)

**Comment by SchoolyB** [comment]
Closed in #109
