### ISSUE TITLE
Build a User Flow for v0.1

### ISSUE THREAD

**Issue by Inter3sted** [Stratgg/Stratgg#6]

**Comment by SchoolyB** [comment]
![Image](https://github.com/Stratgg/Stratgg/assets/110133622/601038cc-0076-450a-a67a-6855a7f50d3c)

**Comment by SchoolyB** [comment]
![Untitled-2022-12-31-1458](https://github.com/Stratgg/Stratgg/assets/110133622/d8c58c92-c149-4e5a-8650-89f23f6db359)
